const stateKey="greenwaveAdminV3";
const demo={
stats:[["01","Fresh releases"],["02","High-quality audio"],["03","Fast downloads"],["04","Creator-focused"]],
categories:[["AF","Afrobeats","Explore sounds"],["HH","Hip-Hop","Explore sounds"],["AM","Amapiano","Explore sounds"],["RB","R&B","Explore sounds"],["GO","Gospel","Explore sounds"],["PC","Podcasts","Explore sounds"]],
artists:[["01","Artist One","Afrobeats"],["02","Artist Two","Amapiano"],["03","Artist Three","R&B"],["04","Artist Four","Hip-Hop"]],
releases:[]
};
let data=JSON.parse(localStorage.getItem(stateKey)||"null")||{settings:{},...demo};

document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.page").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.tab).classList.add("active")});

function bindSettings(){
 document.querySelectorAll("[data-key]").forEach(el=>{const k=el.dataset.key;const [a,b]=k.split(".");if(data.settings[k]!=null)el.value=data.settings[k];el.oninput=()=>{data.settings[k]=el.value}});
}
function renderStats(){document.getElementById("statsEditor").innerHTML=data.stats.map((x,i)=>card(`Stat ${i+1}`,`<div class="mini-grid"><label>Number<input value="${esc(x[0])}" data-stat="${i},0"></label><label>Text<input value="${esc(x[1])}" data-stat="${i},1"></label></div>`)).join("");document.querySelectorAll("[data-stat]").forEach(e=>e.oninput=()=>{let [i,j]=e.dataset.stat.split(",");data.stats[i][j]=e.value})}
function renderCats(){document.getElementById("categoryEditor").innerHTML=data.categories.map((x,i)=>card(x[1],`<div class="mini-grid"><label>Short code<input value="${esc(x[0])}" data-cat="${i},0"></label><label>Name<input value="${esc(x[1])}" data-cat="${i},1"></label><label>Supporting text<input value="${esc(x[2])}" data-cat="${i},2"></label></div>`)).join("");document.querySelectorAll("[data-cat]").forEach(e=>e.oninput=()=>{let [i,j]=e.dataset.cat.split(",");data.categories[i][j]=e.value})}
function renderArtists(){document.getElementById("artistEditor").innerHTML=data.artists.map((x,i)=>card(x[1],`<div class="mini-grid"><label>Avatar text<input value="${esc(x[0])}" data-art="${i},0"></label><label>Name<input value="${esc(x[1])}" data-art="${i},1"></label><label>Category<input value="${esc(x[2])}" data-art="${i},2"></label></div>`)).join("");document.querySelectorAll("[data-art]").forEach(e=>e.oninput=()=>{let [i,j]=e.dataset.art.split(",");data.artists[i][j]=e.value})}
function renderReleases(){document.getElementById("releaseEditor").innerHTML=data.releases.map((x,i)=>card(x.title||"Untitled",`<div class="mini-grid"><label>Title<input value="${esc(x.title||"")}" data-rel="${i},title"></label><label>Artist<input value="${esc(x.artist||"")}" data-rel="${i},artist"></label><label>Category<input value="${esc(x.category||"")}" data-rel="${i},category"></label><label>Cover image URL<input value="${esc(x.cover||"")}" data-rel="${i},cover"></label><label>Audio URL<input value="${esc(x.audio||"")}" data-rel="${i},audio"></label><label>Download count<input type="number" value="${Number(x.downloads||0)}" data-rel="${i},downloads"></label><label>Featured<select data-rel="${i},featured"><option ${x.featured?"selected":""}>true</option><option ${!x.featured?"selected":""}>false</option></select></label></div><button class="remove" data-remove="${i}">Delete release</button>`)).join("")||'<div class="notice">No releases yet. Add one above.</div>';document.querySelectorAll("[data-rel]").forEach(e=>e.oninput=()=>{let [i,k]=e.dataset.rel.split(",");data.releases[i][k]=e.value});document.querySelectorAll("[data-remove]").forEach(e=>e.onclick=()=>{data.releases.splice(Number(e.dataset.remove),1);renderReleases()})}
function card(title,body){return `<div class="repeat-card"><div class="repeat-head"><strong>${esc(title)}</strong></div>${body}</div>`}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
document.getElementById("addRelease").onclick=()=>{data.releases.push({title:"New release",artist:"",category:"Afrobeats",cover:"",audio:"",downloads:0,featured:false});renderReleases()};
document.getElementById("importDemo").onclick=()=>{data.releases=[{title:"Midnight Drive",artist:"Artist One",category:"Afrobeats",downloads:4821,featured:true},{title:"Golden Hour",artist:"Artist Two",category:"Amapiano",downloads:3910,featured:true},{title:"No Pressure",artist:"Artist Three",category:"Hip-Hop",downloads:3254,featured:false},{title:"Afterglow",artist:"Artist Four",category:"R&B",downloads:2876,featured:false}];renderReleases()};
document.getElementById("saveLocal").onclick=()=>{localStorage.setItem(stateKey,JSON.stringify(data));document.getElementById("status").textContent="Saved locally at "+new Date().toLocaleString()};
document.getElementById("downloadConfig").onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="greenwave-content.json";a.click();URL.revokeObjectURL(a.href)};
document.getElementById("importConfig").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{data=JSON.parse(r.result);bindSettings();renderAll();document.getElementById("status").textContent="Imported successfully."}catch{document.getElementById("status").textContent="Invalid JSON file."}};r.readAsText(f)};
function renderAll(){renderStats();renderCats();renderArtists();renderReleases()}
bindSettings();renderAll();